### ISSUE TITLE
Hey there :)

### ISSUE THREAD

**Issue by o0Ignition0o** [VaranTavers/parrot_ar_drone#1]
Hey there :)

I'm Jeremy, and I'm reaching out to you because I'm part of the unofficial Aerorust Working group https://github.com/AeroRust, a group trying to increase awareness of Rust and trying to fly stuff using our favorite language 😁 

We've been working our way towards drone sdks among other things and we just noticed that's what you're working on as well!

We would love to be able to talk to you maybe on Discord or something!
Wanna join us ? 🚀 

Here's a link to our discord, we would love to hear from you :) https://discord.gg/2swXt9

**Comment by VaranTavers** [comment]
Hey!  :D
I feel honored, by such an offer, however I'm not sure that I'd fit in. I only have a very basic Rust (and programming for the matter) knowledge, and little to no knowledge about flying drones (except for this API, which is a rewritten version of the ps_drone python API), plus right now I can't spare much time, since this is the year I'll get (hopefully) my bachelors degree, and I really have to put a lot of effort to make everything work until that.
Maybe later, when I'm done with this I could be of help, however I can't promise anything. I'm really bad with planning ahead.

Thanks again, for the invitation, and I hope that you will be successful in your mission, Rust is truly a language, that more people should be aware of.

**Comment by o0Ignition0o** [comment]
Oh I totally understand, no big deal at all!

If you ever change your mind and / or wanna hang out on discord feel free to do so, no strings attached!
The rewrite looks great, I hope to read from you someday, and I wish you good luck for your bachelors degree! :D
